package com.wirekey.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import android.os.SystemClock
import com.wirekey.WireKeyApp
import com.wirekey.util.HidKeyCodes
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withTimeoutOrNull
import java.io.IOException
import java.util.concurrent.ConcurrentHashMap
import kotlin.random.Random

/**
 * Plays real recorded MacBook keystroke click sounds in sync with keystrokes sent during a
 * send (see TypingSessionManager's onCharacterDown/onBackspace* call sites, and
 * LiveModeViewModel's). Sounds are pre-sliced per physical key by
 * scripts/generate_macbook_pack.py from real keystroke recordings into
 * assets/sounds/<packId>/.
 *
 * All public functions are non-suspend, fire-and-forget: each launches its own coroutine
 * on [engineScope] so the keystroke send loop calling them is never suspended or delayed
 * by audio work.
 *
 * WHAT MAKES THIS SOUND LIKE TYPING RATHER THAN A SAMPLER
 * -------------------------------------------------------
 * Three properties of real typing that a naive one-sample-per-key player loses, and which
 * together were what made this engine's output read as an indistinct burst:
 *
 *  1. *A keypress is one event, not two.* The release click follows the press by the
 *     dwell time -- how long the finger actually rests on the key, 60-110 ms. An earlier
 *     revision fired the release from the HID key-up report, which TypingSessionManager
 *     sends 15 ms after key-down purely because that is a reliable HID inter-report gap.
 *     At 15 ms the release lands inside the press's own transient and the pair fuses into
 *     one smeared double-hit. Release timing is therefore modelled here and deliberately
 *     decoupled from HID report timing -- [onCharacterDown] schedules its own release, and
 *     there is no key-up entry point.
 *
 *  2. *Held keys click once.* Auto-repeat is generated by the host OS while the key stays
 *     physically down, so a held backspace is one press click, silence, then one release
 *     click -- not one click per repeat. See [onBackspaceHoldStart]/[onBackspaceHoldEnd].
 *
 *  3. *No two strokes are equal.* Force varies by finger and stroke, and the two hands are
 *     ~30 cm apart. Per-stroke gain here spans about 8 dB (it previously spanned 0.3 dB,
 *     which is what produced the machine-gun uniformity) and each key is panned to its
 *     typing hand. Repeated letters also draw from several genuinely different recorded
 *     strikes of that key rather than replaying one waveform.
 */
@OptIn(ExperimentalCoroutinesApi::class)
class AcousticTypingEngine(private val context: Context) {

    // USAGE_MEDIA (not USAGE_ASSISTANCE_SONIFICATION) deliberately: sonification routes
    // through Android's "system sounds" stream, which defaults to much lower volume than
    // media on most phones and often isn't even reachable via the volume rocker while an
    // app is in the foreground. Media volume is what users actually expect to control this.
    //
    // CONTENT_TYPE_MUSIC (not CONTENT_TYPE_SONIFICATION) deliberately too: pairing a
    // sonification content type with a media usage is an unusual combination that some
    // OEM audio policies apply their quieter "system beep" loudness/ducking curve to even
    // though usage says MEDIA -- CONTENT_TYPE_MUSIC gets the standard, un-ducked, full-loud
    // media playback curve every device tunes for actual audible content.
    private val soundPool = SoundPool.Builder()
        .setMaxStreams(MAX_STREAMS)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_MEDIA)
                .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
                .build()
        )
        .build()

    // Every read/write of the cadence/backspace state below, every pack load, and every
    // soundPool.play() call happens on this single dedicated (not shared) dispatcher, so
    // that state never needs a Mutex despite being touched by many concurrent keystroke
    // events. Deliberately not TypingSessionManager's own Dispatchers.IO send loop.
    private val engineScope = CoroutineScope(SupervisorJob() + Dispatchers.Default.limitedParallelism(1))

    @Volatile private var enabled: Boolean = true

    // Sound-name ("KeyA_down") -> the SoundPool ids of that key's variants, for the
    // currently-selected pack. Published via a single reference swap after the *new* pack is
    // fully loaded, so no reader ever observes a partially-built map; the *old* pack's ids
    // are only unload()ed after a grace delay so in-flight play() calls from just before a
    // pack switch can't collide with ids SoundPool has already recycled for the new pack.
    @Volatile private var soundIds: Map<String, List<Int>> = emptyMap()

    // Cadence/backspace-rhythm state -- only ever touched from engineScope, so plain vars
    // (no @Volatile/Mutex needed) are safe here despite being read-modify-write.
    private var lastKeyDownUptime: Long = 0L
    private var lastGapMs: Long = NORMAL_GAP_MS
    private var backspaceHeld: Boolean = false
    // Last variant played per sound name, so a repeated letter never replays the same
    // recorded strike twice in a row -- the most audible sampler tell there is.
    private val lastVariant = HashMap<String, Int>()

    // SoundPool.load() is asynchronous -- it returns a sample id immediately but the actual
    // decode happens on a separate thread, and play()ing an id before its decode finishes is
    // a *silent* no-op (no exception, no sound). Keyed by sample id so the single shared
    // listener below can resolve exactly the load loadPack() is waiting on, even if a pack
    // switch starts a new batch of loads while old ones are still in flight.
    private val pendingLoads = ConcurrentHashMap<Int, CompletableDeferred<Boolean>>()

    init {
        soundPool.setOnLoadCompleteListener { _, sampleId, status ->
            pendingLoads.remove(sampleId)?.complete(status == 0)
        }
        engineScope.launch {
            WireKeyApp.settingsRepository.acousticFeedbackEnabled.collect { enabled = it }
        }
        engineScope.launch {
            WireKeyApp.settingsRepository.soundPackId.collect { packId -> loadPack(packId) }
        }
    }

    /**
     * Clears cadence/backspace state without touching loaded sounds. Call at the start of
     * every fresh send so a restart never inherits timing state left over from a cancelled
     * previous send.
     */
    fun resetCadenceState() {
        engineScope.launch {
            lastKeyDownUptime = 0L
            lastGapMs = NORMAL_GAP_MS
            backspaceHeld = false
            lastVariant.clear()
        }
    }

    /**
     * One complete keypress: the press click now, and this key's release click after a
     * realistic dwell. There is deliberately no key-up entry point -- see the class doc.
     *
     * [now] is sampled by the *caller*, synchronously, at the moment the keystroke is
     * actually sent. Reading the clock inside the coroutine instead would measure when the
     * engine's dispatcher got round to this stroke, which under a fast send is queueing
     * latency rather than typing cadence.
     */
    fun onCharacterDown(char: Char, now: Long = SystemClock.uptimeMillis()) {
        if (!enabled) return
        val (keyCode, needsShift) = HidKeyCodes.charMap[char] ?: return
        val keyName = HidKeyCodes.physicalKeyName[keyCode] ?: return
        strike(keyName, now, needsShift)
    }

    /**
     * One complete keypress for a non-character key identified by its HID key code
     * (Backspace, Enter, Tab, ...). Keys with no recorded sound in the pack -- the arrow
     * cluster, for instance -- resolve to nothing and stay silent rather than borrowing
     * some other key's click.
     */
    fun onKeyCodeDown(keyCode: Int, now: Long = SystemClock.uptimeMillis()) {
        if (!enabled) return
        val keyName = HidKeyCodes.physicalKeyName[keyCode] ?: return
        strike(keyName, now, needsShift = false)
    }

    /** A single discrete backspace tap: press plus its own release. */
    fun onBackspaceTap(now: Long = SystemClock.uptimeMillis()) {
        if (!enabled) return
        strike("Backspace", now, needsShift = false)
    }

    /**
     * The key going down at the start of a held-backspace run. The repeats the host OS
     * generates while it stays down are silent -- nothing is physically moving -- so this
     * plays exactly one press click and waits for [onBackspaceHoldEnd].
     */
    fun onBackspaceHoldStart(now: Long = SystemClock.uptimeMillis()) {
        if (!enabled) return
        engineScope.launch {
            backspaceHeld = true
            noteGap(now)
            playSlice("Backspace_down", DOWN_PRIORITY, strokeGain(), "Backspace")
        }
    }

    /** The key finally coming back up after a held-backspace run: one release click. */
    fun onBackspaceHoldEnd() {
        if (!enabled) return
        engineScope.launch {
            if (!backspaceHeld) return@launch
            backspaceHeld = false
            playSlice("Backspace_up", UP_PRIORITY, strokeGain() * RELEASE_GAIN, "Backspace")
        }
    }

    // Press now, release after this stroke's dwell time. Runs the whole keypress on one
    // coroutine so the release can never be reordered ahead of its own press.
    private fun strike(keyName: String, now: Long, needsShift: Boolean) {
        engineScope.launch {
            noteGap(now)
            val gain = strokeGain()

            if (needsShift) {
                // Shift is pressed and held *before* the letter, so it leads rather than
                // stacking onto the letter's transient, and is struck lightly because the
                // hand is already resting on it. Its release falls after the letter and is
                // too quiet to be worth modelling.
                //
                // The lead is much shorter than a real one (a typist holds shift 50-100 ms
                // ahead) because we only learn a capital is coming at the moment it is
                // sent: the sequence can only start at the keystroke, so any lead shows up
                // as the *letter* being late rather than the shift being early. ~30 ms is
                // enough for two transients to read as separate events while keeping the
                // letter close enough to its keystroke to feel simultaneous.
                playSlice("ShiftLeft_down", MODIFIER_PRIORITY, gain * SHIFT_GAIN, "ShiftLeft")
                delay(shiftLeadMs())
            }

            playSlice("${keyName}_down", DOWN_PRIORITY, gain, keyName)

            delay(dwellMs())
            playSlice("${keyName}_up", UP_PRIORITY, gain * RELEASE_GAIN, keyName)
        }
    }

    private fun noteGap(now: Long) {
        lastGapMs = if (lastKeyDownUptime == 0L) NORMAL_GAP_MS else (now - lastKeyDownUptime)
        lastKeyDownUptime = now
    }

    /**
     * How long the finger rests on the key. Bounded by the current typing gap so that at
     * high WPM a release can't still be sounding when the next key is struck -- which is
     * both physically what fast typists do (shorter, lighter strokes) and what keeps
     * consecutive strokes individually audible.
     */
    private fun dwellMs(): Long {
        val natural = Random.nextLong(DWELL_MIN_MS, DWELL_MAX_MS)
        val ceiling = (lastGapMs * DWELL_GAP_FRACTION).toLong()
        return natural.coerceAtMost(ceiling).coerceAtLeast(DWELL_FLOOR_MS)
    }

    private fun shiftLeadMs(): Long =
        Random.nextLong(SHIFT_LEAD_MIN_MS, SHIFT_LEAD_MAX_MS)
            .coerceAtMost((lastGapMs / 2).coerceAtLeast(SHIFT_LEAD_MIN_MS))

    /**
     * Per-stroke gain, spanning roughly 8 dB. Real typing is uneven: fingers differ in
     * strength, individual strokes differ in force, and strokes get lighter as the hands
     * speed up. A near-constant gain (this was 0.97..1.0 before) is the single most
     * mechanical-sounding thing a key sampler can do.
     *
     * Finger strength is applied in [playSlice], which knows the key; this is the
     * stroke-to-stroke part.
     */
    private fun strokeGain(): Float {
        val variation = Random.nextDouble(STROKE_GAIN_MIN, 1.0).toFloat()
        val cadence = when {
            lastGapMs < FAST_GAP_MS -> FAST_STROKE_GAIN
            lastGapMs > SLOW_GAP_MS -> SLOW_STROKE_GAIN
            else -> 1.0f
        }
        return variation * cadence
    }

    /**
     * Slight per-stroke pitch variation. Real strikes vary in exactly where and how hard
     * the key is hit, which shifts its timbre a little; without this, three variants still
     * cycle audibly on long repeated runs.
     */
    private fun rateJitter(): Float = Random.nextDouble(0.955, 1.045).toFloat()

    private fun playSlice(name: String, priority: Int, gain: Float, keyName: String) {
        val variants = soundIds[name] ?: return
        if (variants.isEmpty()) return

        val id = if (variants.size == 1) {
            variants[0]
        } else {
            // Pick any variant except the one this key played last.
            val previous = lastVariant[name] ?: -1
            var index = Random.nextInt(variants.size)
            if (index == previous) index = (index + 1) % variants.size
            lastVariant[name] = index
            variants[index]
        }

        val finger = KeyboardAcoustics.fingerFor(keyName)
        val volume = (gain * finger.strength).coerceIn(0f, 1f)
        // Gentle pan toward the hand that types this key. Only the far channel is
        // attenuated, so panning never costs overall loudness.
        val left = volume * (1f - (finger.pan.coerceAtLeast(0f)) * PAN_DEPTH)
        val right = volume * (1f - (-finger.pan).coerceAtLeast(0f) * PAN_DEPTH)

        soundPool.play(id, left, right, priority, 0, rateJitter().coerceIn(0.5f, 2.0f))
    }

    // Runs on engineScope: builds the new pack's sound map, waits for every sound to actually
    // finish decoding (see pendingLoads' doc above), and only then publishes it -- so the
    // first keystrokes right after a pack switch can never silently land on a still-loading
    // sample id. Frees the previous pack's ids after a grace delay after that. See soundIds's
    // doc above.
    private suspend fun loadPack(packId: String) {
        val newIds = mutableMapOf<String, List<Int>>()
        val loading = mutableListOf<CompletableDeferred<Boolean>>()

        for (keyName in CURATED_KEYS) {
            for (suffix in SUFFIXES) {
                val variants = mutableListOf<Int>()
                // Variants are written as <Key>_<down|up>_<n>.wav with n contiguous from 0,
                // so the first gap is the end of the list. A pack that ships fewer (or no)
                // variants for a key simply plays what it has.
                for (variant in 0 until MAX_VARIANTS) {
                    val assetPath = "sounds/$packId/${keyName}_${suffix}_$variant.wav"
                    try {
                        context.assets.openFd(assetPath).use { afd ->
                            val deferred = CompletableDeferred<Boolean>()
                            val id = soundPool.load(afd, DOWN_PRIORITY)
                            pendingLoads[id] = deferred
                            variants += id
                            loading += deferred
                        }
                    } catch (e: IOException) {
                        break
                    }
                }
                if (variants.isNotEmpty()) newIds["${keyName}_$suffix"] = variants
            }
        }

        // Bounded by a timeout so a load that never calls back (shouldn't happen, but
        // SoundPool offers no hard guarantee) can't wedge every future pack switch forever --
        // worst case some sounds in a huge/malformed pack stay silent instead of the whole
        // engine getting stuck mid-switch.
        withTimeoutOrNull(LOAD_TIMEOUT_MS) {
            loading.forEach { it.await() }
        }

        val oldIds = soundIds
        soundIds = newIds
        lastVariant.clear()

        delay(UNLOAD_GRACE_MS)
        for (ids in oldIds.values) {
            for (id in ids) soundPool.unload(id)
        }
    }

    companion object {
        // Clips are ~100 ms (press) and 45 ms (release), so even at 120 WPM only a couple
        // overlap. A large stream budget bought nothing but the ability to pile up tails.
        private const val MAX_STREAMS = 12
        private const val MAX_VARIANTS = 4

        // Presses outrank releases: if the pool ever does run out of streams, the event that
        // must stay audible is the one that marks the keystroke.
        private const val DOWN_PRIORITY = 3
        private const val UP_PRIORITY = 1
        private const val MODIFIER_PRIORITY = 2

        private const val UNLOAD_GRACE_MS = 400L
        private const val LOAD_TIMEOUT_MS = 5000L

        // Dwell: measured key-down-to-key-up for touch typists sits around 60-110 ms and
        // shortens as they speed up.
        private const val DWELL_MIN_MS = 62L
        private const val DWELL_MAX_MS = 108L
        private const val DWELL_FLOOR_MS = 32L
        private const val DWELL_GAP_FRACTION = 0.62f

        private const val SHIFT_LEAD_MIN_MS = 22L
        private const val SHIFT_LEAD_MAX_MS = 36L
        private const val SHIFT_GAIN = 0.72f

        // The clips are already mastered ~13.5 dB below their press; this is the extra
        // playback trim that puts a release where it belongs relative to its own press.
        private const val RELEASE_GAIN = 0.80f

        private const val STROKE_GAIN_MIN = 0.62
        private const val FAST_STROKE_GAIN = 0.88f
        private const val SLOW_STROKE_GAIN = 1.0f

        private const val PAN_DEPTH = 0.42f

        private const val FAST_GAP_MS = 90L
        private const val SLOW_GAP_MS = 320L
        private const val NORMAL_GAP_MS = 200L

        private val SUFFIXES = arrayOf("down", "up")

        // Every physical key WireKey's HID layer can send a report for, plus ShiftLeft for
        // the shift-chord pre-click. Must match DATASET_KEYS + the derived-key names in
        // scripts/generate_macbook_pack.py, which is what actually produced the asset
        // files this list is used to look up.
        private val CURATED_KEYS: List<String> =
            (0..25).map { "Key" + ('A' + it) } +
                (0..9).map { "Digit$it" } +
                listOf(
                    "Minus", "Equal", "BracketLeft", "BracketRight", "Backslash",
                    "Semicolon", "Quote", "Backquote", "Comma", "Period", "Slash",
                ) +
                listOf("Space", "Enter", "Tab", "Backspace") +
                listOf("ShiftLeft")
    }
}
